<project xmlns="http://maven.apache.org/POM/4.0.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.antmedia</groupId>
  <artifactId>parent</artifactId>
  <version>3.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  
    <name>Ant Media Server :: Parent</name>
    <description>Ant Media Server Parent Project</description>
    <url>https://github.com/antmedia/Ant-Media-Server</url>
    <inceptionYear>2016</inceptionYear>
    	<parent>
		<groupId>org.red5</groupId>
		<artifactId>red5-parent</artifactId>
		<version>1.2.3</version>
	</parent>
	<organization>
		<name>Ant Media</name>
		<url>https://github.com/antmedia</url>
	</organization>
	<licenses>
		<license>
			<name>Apache 2</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
			<comments>A business-friendly OSS license</comments>
		</license>
	</licenses>
	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>
    
    <scm>
        <url>https://github.com/antmedia/Ant-Media-Server</url>
        <connection>scm:git:git@antmedia/Ant-Media-Server-Parent.git</connection>
        <developerConnection>scm:git:git@github.com:antmedia/Ant-Media-Server-Parent.git</developerConnection>
    </scm>
    <developers>
    	<developer>
            <id>Ant Media</id>
            <email>contact@antmedia.io</email>
        </developer>
    </developers>
    <properties>
    	<java.version>17</java.version>
    	<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<maven-gpg-plugin.version>3.1.0</maven-gpg-plugin.version>
		<maven-bundle-plugin.version>5.1.9</maven-bundle-plugin.version>
		<maven-source-plugin.version>3.3.0</maven-source-plugin.version>
		<maven-dependency-plugin.version>3.6.1</maven-dependency-plugin.version>
		<maven-war-plugin.version>3.4.0</maven-war-plugin.version>
		<maven-assembly-plugin.version>3.6.0</maven-assembly-plugin.version>
		<maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
		<jacoco-maven-plugin.version>0.8.12</jacoco-maven-plugin.version>
		<exec-maven-plugin.version>3.1.1</exec-maven-plugin.version>
		<maven-release-plugin.version>3.0.1</maven-release-plugin.version>
		<nexus-staging-maven-plugin.version>1.6.13</nexus-staging-maven-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <skipTests>true</skipTests>
        <spring.version>6.2.5</spring.version>
        <spring-security-core.version>6.3.8</spring-security-core.version>
        <mina.version>2.0.27</mina.version>
        <slf4j.version>2.0.9</slf4j.version>
        <logback.version>1.5.3</logback.version>
        <quartz.version>2.5.0-rc1</quartz.version>
        <bc.version>1.78.1</bc.version>
        <junit5.version>5.10.2</junit5.version>
        <junit.version>4.13.2</junit.version>
        <commons-beanutils.version>1.9.4</commons-beanutils.version>
        <commons-codec.version>1.16.0</commons-codec.version>
        <commons-lang3.version>3.13.0</commons-lang3.version>
        <commons-io>2.15.0</commons-io>
        <tomcat.version>10.1.40</tomcat.version>
        <smiley-http-proxy-servlet.version>2.0</smiley-http-proxy-servlet.version>
        <red5-io.version>1.2.2</red5-io.version> 
        <cors-filter.version>3.0</cors-filter.version>
		<maven-failsafe-plugin.version>3.2.2</maven-failsafe-plugin.version>
		<javacpp.version>1.5.11</javacpp.version>
		<javacpp.ffmpeg.version>7.1-${javacpp.version}</javacpp.ffmpeg.version>
		<javacpp.cuda.version>12.6-9.5-${javacpp.version}</javacpp.cuda.version>
		<javacpp.srt.version>1.5.3-${javacpp.version}</javacpp.srt.version>
		<jersey.version>3.1.3</jersey.version>
		<jackson-databind.version>2.18.1</jackson-databind.version>
		<mapdb.version>3.0.10</mapdb.version>
		<vertx-core.version>4.5.10</vertx-core.version>
		<jsr305.version>3.0.2</jsr305.version>      
		<kafka-streams.version>3.9.0</kafka-streams.version>
		<tensorflow.version>1.15.0</tensorflow.version>
		<httpmime.version>4.5.14</httpmime.version>
		<mockito-core.version>5.12.0</mockito-core.version>
		<awaitility.version>4.2.0</awaitility.version>
		<protobuf-java.version>3.25.5</protobuf-java.version>
		<morphia.version>2.4.13</morphia.version>
		<json-simple.version>1.1.1</json-simple.version>
		<owasp.version>8.4.3</owasp.version>
		<selenium-java.version>4.18.1</selenium-java.version>
		<webdrivermanager.version>6.1.0</webdrivermanager.version>
		<netty.version>4.1.118.Final</netty.version>
		<redisson.version>3.24.3</redisson.version>
		<gson.version>2.10.1</gson.version>
		<jwks-rsa.version>0.22.1</jwks-rsa.version>
		<java-jwt.version>4.4.0</java-jwt.version>
		<aws-java-sdk-bom.version>1.12.683</aws-java-sdk-bom.version>
		<maven-javadoc-plugin.version>3.6.2</maven-javadoc-plugin.version>
		<maven-jar-plugin.version>3.3.0</maven-jar-plugin.version>
		<maven-surefire-plugin.version>3.3.0</maven-surefire-plugin.version>
		<maven-scm-plugin.version>2.0.1</maven-scm-plugin.version>
		<maven-project-info-reports-plugin.version>3.4.5</maven-project-info-reports-plugin.version>
		<tyrus.version>2.1.4</tyrus.version>
		<firebase.version>9.3.0</firebase.version>
		<pushy.version>0.15.4</pushy.version>
		<swagger-jaxrs2-jakarta.version>2.2.21</swagger-jaxrs2-jakarta.version>

    </properties>
    <repositories>
        <repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
            <layout>default</layout>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>sonatype-snapshots</id>
            <name>Sonatype Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
        <repository>
            <id>sonatype-releases</id>
            <name>Sonatype Releases</name>
            <url>https://oss.sonatype.org/content/repositories/releases</url>
        </repository>
    </repositories>
    <dependencyManagement>
        <dependencies>
			<dependency>
				<groupId>com.amazonaws</groupId>
				<artifactId>aws-java-sdk-bom</artifactId>
				<version>${aws-java-sdk-bom.version}</version>
				<type>pom</type>
				<scope>import</scope>
				<exclusions>
					<exclusion>
						<artifactId>com.fasterxml.jackson.core</artifactId>
						<groupId>jackson-annotations</groupId>
					</exclusion>
				</exclusions>
			</dependency>
	        <dependency>
				<groupId>org.red5</groupId>
				<artifactId>red5-io</artifactId>
				<version>${red5-io.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-context-support</artifactId>
				<version>${spring.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-core</artifactId>
				<version>${spring.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-context</artifactId>
				<version>${spring.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-web</artifactId>
				<version>${spring.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-webmvc</artifactId>
				<version>${spring.version}</version>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-core</artifactId>
				<version>${spring-security-core.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-config</artifactId>
				<version>${spring-security-core.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-web</artifactId>
				<version>${spring-security-core.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-crypto</artifactId>
				<version>${spring-security-core.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-oauth2-authorization-server</artifactId>
				<version>1.4.0</version>
			</dependency>
	
	
			<!-- OAuth2 dependencies -->
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-oauth2-client</artifactId>
				<version>${spring-security-core.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-oauth2-jose</artifactId>
				<version>${spring-security-core.version}</version>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>${slf4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.mina</groupId>
				<artifactId>mina-parent</artifactId>
				<version>${mina.version}</version>
				<type>pom</type>
			</dependency>
			<dependency>
			    <groupId>org.apache.kafka</groupId>
			    <artifactId>kafka-streams</artifactId>
			    <version>${kafka-streams.version}</version>
       		</dependency>
			<dependency>
			    <groupId>org.bytedeco</groupId>
			    <artifactId>javacpp</artifactId>
			    <version>${javacpp.version}</version>
       		</dependency>
       		<dependency>
            	<groupId>org.glassfish.tyrus</groupId>
            	<artifactId>tyrus-server</artifactId>
            	<version>${tyrus.version}</version>
        	</dependency>
         	<dependency>
            	<groupId>org.glassfish.tyrus</groupId>
            	<artifactId>tyrus-container-grizzly-server</artifactId>
            	<version>${tyrus.version}</version>
         	</dependency>
         	<dependency>
				<groupId>org.glassfish.tyrus.bundles</groupId>
				<artifactId>tyrus-standalone-client</artifactId>
				<version>${tyrus.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>

		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<configuration>
					<release>${java.version}</release>
					<fork>true</fork>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-source-plugin</artifactId>
				<version>${maven-source-plugin.version}</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>${maven-javadoc-plugin.version}</version>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<verbose>true</verbose>
					<failOnError>false</failOnError>
					<sourcepath>${basedir}/src/main/java</sourcepath>
					<includeDependencySources>false</includeDependencySources>
					<dependencySourceIncludes>
						<dependencySourceInclude>org.red5:*</dependencySourceInclude>
					</dependencySourceIncludes>
					<detectOfflineLinks>false</detectOfflineLinks>
					<links>
						<link>http://download.oracle.com/javase/11/docs/api</link>
						<link>http://docs.spring.io/spring/docs/${spring.version}/javadoc-api</link>
					</links>
					<tags>
						<tag>
							<name>todo</name>
							<!-- todo tag for all places -->
							<placement>a</placement>
							<head>To do:</head>
						</tag>
					</tags>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>${maven-jar-plugin.version}</version>
				<executions>
					<execution>
						<configuration>
							<archive>
								<manifest>
									<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
								</manifest>
								<manifestEntries>
									<SCM-Revision>${buildNumber}</SCM-Revision>
									<Implementation-Build>${buildNumber}</Implementation-Build>
								</manifestEntries>
							</archive>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>${maven-dependency-plugin.version}</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
							<excludeTransitive>true</excludeTransitive>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven-surefire-plugin.version}</version>
				<configuration>					
					<skipTests>${skipTests}</skipTests>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>${maven-project-info-reports-plugin.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-scm-plugin</artifactId>
				<version>${maven-scm-plugin.version}</version>
				<configuration>
					<connectionType>connection</connectionType>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>${maven-bundle-plugin.version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<artifactId>maven-release-plugin</artifactId>
				<version>${maven-release-plugin.version}</version>
				<configuration>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<useReleaseProfile>false</useReleaseProfile>
					<releaseProfiles>release</releaseProfiles>
					<goals>deploy</goals>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.sonatype.plugins</groupId>
				<artifactId>nexus-staging-maven-plugin</artifactId>
				<version>${nexus-staging-maven-plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<serverId>ossrh</serverId>
					<nexusUrl>https://oss.sonatype.org/</nexusUrl>
					<autoReleaseAfterClose>true</autoReleaseAfterClose>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>${maven-gpg-plugin.version}</version>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
						<configuration>
			                <gpgArguments>
			                    <arg>--pinentry-mode</arg>
			                    <arg>loopback</arg>
			                </gpgArguments>
          				</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

  
